### PR TITLE
Validatable corrections to the CED VDER example

### PR DESCRIPTION
**Pull request by nick-turchak-fluxtailor**
Corrected `tariff_book_leaf_ranges`, `time_of_use_periods` and `minimum_charges` for the CED XML sample. Added `tariff_statements` - the charge data itself is populated with mock data <value>0</value> in each statement charge.

### CODE REVIEW

**Review by jonah-bossewitch-fluxtailor — COMMENTED** [review]
Hi @nick-turchak-fluxtailor Hi @KlaarDeSchepper,

Nick prepped this PR w/ the CED VDER example. 

Should these files be renamed according to these conventions?  https://fluxtailor-wiki.atlassian.net/wiki/spaces/RIRPDA/pages/94863362/How-to+add+or+update+an+IEDR+Rate+Plan+Data+Test+Case

I believe the tarrif pdf docs should also be included.

Finally, we want to start referring to the schema here https://raw.githubusercontent.com/Flux-Tailor/rate-plan-schema/refs/tags/v0.9/<schema.xsd> instead of file:../../../rate-plan-schema/<schema.xsd>.   Should be a search and replace.

Klaar - do you want this PR merged, or should it be updated first?

**Comment by KlaarDeSchepper** [comment]
Hi Jonah Thanks for the follow up. Let’s update prior to merging. Yes the files should be renamed per those conventions, please add the instructions for schema reference updates to that same confluence page.Thanks!KlaarOn Sep 26, 2024, at 10:51, Jonah Bossewitch ***@***.***> wrote:﻿
@jonah-bossewitch-fluxtailor commented on this pull request.

Hi @nick-turchak-fluxtailor Hi @KlaarDeSchepper,
Nick prepped this PR w/ the CED VDER example.
Should these files be renamed according to these conventions?  https://fluxtailor-wiki.atlassian.net/wiki/spaces/RIRPDA/pages/94863362/How-to+add+or+update+an+IEDR+Rate+Plan+Data+Test+Case
I believe the tarrif pdf docs should also be included.
Finally, we want to start referring to the schema here https://raw.githubusercontent.com/Flux-Tailor/rate-plan-schema/refs/tags/v0.9/<schema.xsd> instead of file:../../../rate-plan-schema/<schema.xsd>.   Should be a search and replace.
Klaar - do you want this PR merged, or should it be updated first?

**Review by jonah-bossewitch-fluxtailor — CHANGES_REQUESTED** [review]
Please update this PR according to the conventions Klaar specified.

**Comment by nick-turchak-fluxtailor** [comment]
@nick-turchak-fluxtailor @jonah-bossewitch-fluxtailor the 2 requested changes have been made in the latest commit
Please add the tariff PDF docs.

**Review by jonah-bossewitch-fluxtailor — APPROVED** [review]
👍

**Pull request merged**
