### PR TITLE
Tariff book agr rge electric sc8 v0.99.7 dev

### PR DESCRIPTION
**Pull request by aminata-cisse-fluxtailor**
The remaining validation errors are about 22, and all relate to enrollment criteria. My questions are:

1. If the enrollment isn't specified does that automatically make it a "Program Enrollment"? 
2. Is enrollmentCriteria supposed to be a required field? (Without the block, limit, which is right below it, shows a "Invalid content was found starting with element 'limit'. One of '{enrollmentCriteria}' is expected," error. 

Would appreciate any set of eyes and support in answering my questions so that I can fully complete this test case, thank you.

### CODE REVIEW

**Review by jonah-bossewitch-fluxtailor — CHANGES_REQUESTED** [review]
Hi @aminata-cisse-fluxtailor,

Did you intend to introduce changes to the v0.99.5-dev xml instance?   Can you please remove this file from the PR and leave it as the version from two months ago *https://github.com/Flux-Tailor/rate-plan-test-cases/blob/main/AGR/RGE/ELECTRIC/T001_SC8-All/XML/v0.99.5-dev/AGR_RGE_E_T001_SC8-All_tariff_books_2024-10-29T1215-4.xml (commit 613efce)

I believe you have applied all of the relevant changes to 0.99.7, but you should double check.

**Comment by aminata-cisse-fluxtailor** [comment]
Thanks for catching that Jonah, I successfully restored the contents to the 99.5. The intended changes in my PR include my work on the /v0.99.7-dev directory.

**Comment by jonah-bossewitch-fluxtailor** [comment]
Hi @acisse44,

I checked in w/ @KlaarDeSchepper  and she confirmed that enrollment is required and when in doubt you can use `VoluntaryEnrollment` unless it is clear that enrollment is mandatory.  This information comes from the Rate Plan Browser and should have values, under eligibility criteria.   Do you see the enumeration choices here? https://flux-tailor.github.io/rate-plan-documentation/_static/rate-plan-schema-docs/v0.99.7-dev/rate_plan_data_transfer/rate_plan_data_transfer.html

Please checkin today if you have any follow up questions.  Thanks!

**Review by jonah-bossewitch-fluxtailor — CHANGES_REQUESTED** [review]
These elements are mandatory and should not have empty strings.

**Review by jonah-bossewitch-fluxtailor — APPROVED** [review]
🏅 Nice!    Everything looks good from here.

**Pull request merged**
