### PR TITLE
Tariff book cei ced electric sc1 v0.99.7 dev

### PR DESCRIPTION
**Pull request by nick-turchak-fluxtailor**
Correction to commodity

### CODE REVIEW

**Comment by nick-turchak-fluxtailor** [comment]
@KlaarDeSchepper approve the commodity correction please

**Review by jonah-bossewitch-fluxtailor — CHANGES_REQUESTED** [review]
Hi @nick-turchak-fluxtailor,

I see this XML file is validating locally in Oxygen.  I could use a hand resolving the conflicts on this PR. I think this one is older than the others and there is some confusion around the territories placement.  

When you get a chance, can you please review?

**Comment by nick-turchak-fluxtailor** [comment]
@jonah-bossewitch-fluxtailor what do you mean confusion? This stuff looks good to me, I just forgot to add the territories originally and then added them later on.

**Review by jonah-bossewitch-fluxtailor — APPROVED** [review]
I resolved the conflicts and this validates.

**Pull request merged**
